yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit',),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Введите текст',
                            help_text='Введите текст в поле')
    pub_date = models.DateTimeField(verbose_name='Дата публикации',
                                    auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.CASCADE,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Выберите группу')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField(verbose_name='Комментарий',
                            help_text='Введите комментарий в поле',
                            null=True)
    created = models.DateTimeField(verbose_name='Дата публикации',
                                   auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User,
                             related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User,
                               related_name='following',
                               on_delete=models.CASCADE)

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Comment, Follow
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from .utils import get_page
from django.views.decorators.cache import cache_page


@cache_page(20)
def index(request):
    post_roster = Post.objects.all().order_by('-pub_date')
    page_obj = get_page(request, post_roster)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_roster = Post.objects.filter(group=group).order_by('-pub_date')
    page_obj = get_page(request, post_roster)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = (get_object_or_404(User.objects.
              prefetch_related('posts', 'posts__group'),
              username=username))
    post_roster = (Post.objects.all().
                   filter(author=author).order_by('-pub_date'))
    page_obj = get_page(request, post_roster)
    if (not Follow.objects.
            filter(user__id=request.user.id, author=author).exists()):
        following = False
    else:
        following = True
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.all().filter(post=post_id)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return render(request, 'posts:post_detail', post_id=post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id=post.id)
    is_edit = True
    context = {
        'is_edit': is_edit,
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_roster = (Post.objects.all().
                   filter(author__following__user=request.user).
                   order_by('-pub_date'))
    page_obj = get_page(request, post_roster)
    follower_user = Follow.objects.all()
    context = {
        'follower_user': follower_user,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/comment.html
{% load static %}
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-2">
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>    
            {{ field }}
          </div>
          {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 
  </div>

yatube/templates/posts/create_post.html
<!DOCTYPE html>  
{% extends 'base.html' %}
{% load user_filters %}
{% block title|safe %}
Новый пост
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header"> 
            {% if is_edit %}      
            Редактировать запись
            {% else %}
            Новая запись
            {% endif %}            
          </div>
            <div class="card-body">
              {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              {% if is_edit %}
                <form method="post" action="{% url "posts:post_edit"  post.id %}" enctype="multipart/form-data">
              {% else %}
                <form method="post" action="{% url "posts:post_create" %}" enctype="multipart/form-data">
              {% endif %} 
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field }}
                </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %} 
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}              
                  </button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title|safe %}
Подписки пользователя {{ user.get_full_name }}
{% endblock %}
{% block content %}
<div class="container py-5">  
{% include 'includes/switcher.html'%}   
  <h1>
    Подписки пользователя {{ user.get_full_name }}
  </h1>
<article>
  <h2>
    Количество ваших подписок: {{ follower_user.count }} 
  </h2>

{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul> 
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}     
  <p>
    {{ post.text }}
  </p>
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {%if not forloop.last %}
</article>
<hr>
  {% endif %}
{% endfor %}
</div>
<div class="container py-5">
  {% include 'includes/paginator.html'%}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title|safe %}
  Записи группы сообщества {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <header>
    {% block header %}
    <h1>{{ group }}</h1>
    {% endblock %}
  </header>
  <p>
    {{ group.description }}
  </p>
  <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}  
  <p>
    {{ post.text }}
  </p>        
  </article>
  <hr>
  {% endfor %}
<!-- под последним постом нет линии -->
</div>
<div class="container py-5">
  {% include 'includes/paginator.html'%}
</div>
{% endblock %}  

yatube/templates/posts/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title|safe %}
Последние обновления на сайте
{% endblock %}
{% block content %}
<div class="container py-5">     
  <h1>
    Последние обновления на сайте
  </h1>
{% include 'includes/switcher.html'%}
<article>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}     
  <p>
    {{ post.text }}
  </p>
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {%if not forloop.last %}
</article>
<hr>
  {% endif %}
{% endfor %}
</div>
<div class="container py-5">
  {% include 'includes/paginator.html'%}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
{% block title|safe %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{%block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
            <!-- если у поста есть группа -->   
        <li class="list-group-item">
        {% if post.group %}
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.id %}">
            все посты пользователя
          {% endif %}
          </a>
        </li>
        <li class="list-group-item">
          {% if user.username == post.author.username %}
          <a href = "{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
          {% endif %}
        </li>
      </ul>
    </aside>
<article class="col-12 col-md-9">
  <p>
    {{ post.text }}
  </p>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
</article>
{% include 'posts/comment.html' %}
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load thumbnail %}
{% block title|safe %}
Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
{% if following and user.is_authenticated %}
  <a
    class="btn btn-lg btn-light"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button">
    Отписаться
  </a>
{% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button">
      Подписаться
    </a>
 {% endif %}   
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:'d E Y'}}
      </li>
    </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text }}
  </p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a><br>
  </article>
  {% if post.group %}       
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    <hr>
  {% endif %} 
    {% endfor %}      
        <!-- Остальные посты. после последнего нет черты -->
  <div class="container py-5">
    {% include 'includes/paginator.html'%}
  </div>
</div>
{% endblock %}